#!/usr/bin/env bash

set -xe

: "${GITHUB_USER?Need a GitHub username}"
: "${GITHUB_REPO?Need a repository name}"
: "${GITHUB_BRANCH?Need a GitHub branch}"
: "${GITHUB_TOKEN?Need a GitHub token}"
: "${NPM_TOKEN?Need a npm token}"
: "${PACKAGE_VERSION?Need a package version}"
: "${CI_EMAIL:=Need a email for CI}"

git config --global user.name "CI-NPM-PUBLISHER"
git config --global user.email $CI_EMAIL

if [[ -z "${GITHUB_TOKEN}" ]]; then
  git clone -b "$GITHUB_BRANCH" https://github.com/"$GITHUB_USER"/"$GITHUB_REPO".git
else
  git clone -b "$GITHUB_BRANCH" https://"$GITHUB_TOKEN"@github.com/"$GITHUB_USER"/"$GITHUB_REPO".git
fi

cd $GITHUB_REPO

npm version $PACKAGE_VERSION -m "Release: $PACKAGE_VERSION"
echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
npm publish

git push --tags
github_changelog_generator -t $GITHUB_TOKEN
git add CHANGELOG.md && git commit -m "Added changelog for version $PACKAGE_VERSION"
git push origin $GITHUB_BRANCH

hub pull-request -m "Updated to version $PACKAGE_VERSION" -b develop
hub pull-request -m "Updated to version $PACKAGE_VERSION" -b master