#!/usr/bin/env bash

docker run --rm\
  -e GITHUB_USER=CHANGE \
  -e GITHUB_REPO=CHANGE \
  -e GITHUB_BRANCH=CHANGE \
  -e GITHUB_TOKEN=CHANGE \
  -e NPM_TOKEN=CHANGE \
  -e PACKAGE_VERSION=CHANGE \
  -e CI_EMAIL=CHANGE \
  -e FORCE_COLOR=1 \
   madoos/node-npm-publisher:latest