#!/usr/bin/env bash


docker run \
-e CI_EMAIL=jenkins@gmail.com \
-e GITHUB_REPO=kk-test \
-e GITHUB_USER=madoos \
-e GITHUB_BRANCH=release/test \
-e GITHUB_TOKEN=fef891d8d1d1c445f571cee89fc5109f4d21b879 \
-e NPM_TOKEN=f5be2333-f3bf-4a81-960c-092f377af729 \
-e PACKAGE_VERSION=1.0.19 \
 madoos/node-npm-publisher:latest